### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by hudzikj** [radical-squared/aquatemp#8] opened 2022-08-17 15:15 UTC
Hi,

I have two heat pumps linked to one account.
I have  an error when starting the component.

2022-08-17 16:51:03.559 ERROR (MainThread) [homeassistant.components.climate] aquatemp: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 477, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 702, in async_device_update
    await task
  File "/config/custom_components/aquatemp/climate.py", line 256, in async_update
    await self.login(session)
  File "/config/custom_components/aquatemp/climate.py", line 348, in login
    self._device_code = response_json['object_result'][0]['device_code']
IndexError: list index out of range

Regards

**Comment by radical-squared** [comment] 2022-08-18 13:22
Thanks for reporting. The issue should be fixed in version 2.2.1.

**Comment by radical-squared** [comment] 2022-08-18 14:10
Not sure how two pumps would be handled, though.

**Comment by hudzikj** [comment] 2022-08-18 16:08
Now, regardless of what login details I provide (correct or incorrect), an error appears:

2022-08-18 17:48:32.370 ERROR (MainThread) [custom_components.aquatemp.climate] Error logging in. Will keep on trying.

**Comment by radical-squared** [comment] 2022-08-18 16:22
That's the improved error reporting :) 

No idea what the problem is. Perhaps it's the two pumps. You could try figuring out with curl requests from https://github.com/dst6se/aquatemp/blob/main/heatpump

**Comment by radical-squared** [comment] 2022-08-18 22:01
Please update to 2.2.2 and add the following to the logger section of your configuration.yaml file:
custom_components.aquatemp.climate: debug

**Comment by hudzikj** [comment] 2022-08-19 07:36
For testing purposes, I have created a new account. There is no heat pump assigned. It looks like it gets the nickname correctly, but then an error occurs


2022-08-19 09:29:39.422 DEBUG (MainThread) [custom_components.aquatemp.climate] {'error_code': '0', 'error_msg': 'Success', 'error_msg_code': '', 'object_result': {'role_name': 'User', 'user_type': 'Customer', 'user_id': '1560314985781923840', 'user_name': '#####', 'nick_name': 'artefakt22', 'roleName': 'User', 'x-token': '1469F9099B031FDC65BB3F5AC74D7153', 'real_name': None}, 'is_reuslt_suc': True}
2022-08-19 09:29:39.487 DEBUG (MainThread) [custom_components.aquatemp.climate] {'error_code': '0', 'error_msg': 'Success', 'error_msg_code': '', 'object_result': [], 'is_reuslt_suc': True}
2022-08-19 09:29:39.487 ERROR (MainThread) [custom_components.aquatemp.climate] Error logging in. Will keep on trying.
2022-08-19 09:30:40.430 DEBUG (MainThread) [custom_components.aquatemp.climate] {'error_code': '0', 'error_msg': 'Success', 'error_msg_code': '', 'object_result': {'role_name': 'User', 'user_type': 'Customer', 'user_id': '1560314985781923840', 'user_name': '#####', 'nick_name': 'artefakt22', 'roleName': 'User', 'x-token': '12551847101178190819DF25A8BE190E', 'real_name': None}, 'is_reuslt_suc': True}
2022-08-19 09:30:40.777 DEBUG (MainThread) [custom_components.aquatemp.climate] {'error_code': '0', 'error_msg': 'Success', 'error_msg_code': '', 'object_result': [], 'is_reuslt_suc': True}
2022-08-19 09:30:40.778 ERROR (MainThread) [custom_components.aquatemp.climate] Error logging in. Will keep on trying.
2022-08-19 09:31:39.483 DEBUG (MainThread) [custom_components.aquatemp.climate] {'error_code': '0', 'error_msg': 'Success', 'error_msg_code': '', 'object_result': {'role_name': 'User', 'user_type': 'Customer', 'user_id': '1560314985781923840', 'user_name': '####', 'nick_name': 'artefakt22', 'roleName': 'User', 'x-token': '30A3288A441FA34E8A81E6F8796ED443', 'real_name': None}, 'is_reuslt_suc': True}

**Comment by radical-squared** [comment] 2022-08-19 08:35
Upon successful authentication you get an empty device array. This is an example of a correct response:
```
$ curl -H "x-token: SECRET_TOKEN" -X POST https://cloud.linked-go.com/cloudservice/api/app/device/deviceList.json
{
  "error_code" : "0",
  "error_msg" : "Success",
  "error_msg_code" : "",
  "object_result" : [ {
    "device_status" : "ONLINE",
    "device_name" : null,
    "is_fault" : false,
    "device_id" : "123456789856",
    "device_code" : "34E0E783F4D",
    "product_id" : "1122275963697280512",
    "device_type" : null,
    "device_nick_name" : "Pool"
  } ],
  "is_reuslt_suc" : true
}%     
```


And this is  what you get:
```
$ curl -H "x-token: 1469F9099B031FDC65BB3F5AC74D7153" -X POST https://cloud.linked-go.com/cloudservice/api/app/device/deviceList.json
{
  "error_code" : "0",
  "error_msg" : "Success",
  "error_msg_code" : "",
  "object_result" : [ ],
  "is_reuslt_suc" : true
}%         
```

**Comment by radical-squared** [comment] 2022-08-19 09:38
Try adding one heat pump to the new account and see what the response is

**Comment by hudzikj** [comment] 2022-08-19 10:03
I currently have one heat pump linked to my account. The problem is the same. I suspect this is because these are shared pumps. Perhaps hence the problem with empty "object_result".
At the moment, I do not have access to the main account where the pump is assigned to confirm this.
Now we can close the issue. I will let you know when I check on main account.

Thanks.

**Closed as completed** 2022-08-19 10:04 UTC
