### ISSUE TITLE
HVAC Mode Mapping in v3.0.1 is mixed up

### ISSUE THREAD

**Issue by migueldc73** [radical-squared/aquatemp#29] opened 2023-05-28 15:54 UTC
I am not sure if I am the only one whose HVAC modes were mixed up after the upgrade to v3.0.1 ?
    HASS mode AUTO sets my heatpump on mode COOL
    HASS mode HEAT sets heatpump on mode AUTO
    HASS mode COOL seats heatpump on mode HEAT
    Luckily OFF stays OFF :-)

I solved this partially by changing these lines in const.py :
MODE_TEMPERATURE_OFF = "0"
MODE_TEMPERATURE_HEAT = "1"
MODE_TEMPERATURE_AUTO = "2"
MODE_TEMPERATURE_COOL = "3"

Now it works, but when I change temperature, it still changes them on my heatpump on the wrong modes, so I guess I need to edit some other lines

Anyone else with the same issues or just me ?

**Comment by legantois** [comment] 2023-05-29 08:58
Same issue here:
Auto (in HA) -> Cool (in aquatemp)
Cool (in HA) -> Heat (in aquatemp
Heat (in HA) -> Auto (in Aquatemp)

**Comment by migueldc73** [comment] 2023-05-29 09:04
And there is more : 
when HA reboots, it does not see the Aquatemp HP as ON even though it is on. 

The previous v2.2 actually worked fine with me (albeit with infrequent status updates)

**Comment by Taz-assistant** [comment] 2023-05-29 11:09
Almost same here.
Heat = cool.

And another issue is contant drop in comm between hass and pump.

I did not have these issues with V2.2

Den mån 29 maj 2023 11:04migueldc73 ***@***.***> skrev:

**Comment by elad-bar** [comment] 2023-05-30 10:55
Will check it, probably mapped it incorrectly, sorry,
Can you post diagnostic file and log file in debug taking those actions so i'll be sure i'm mapping it correctly?

Thanks

**Comment by legantois** [comment] 2023-05-30 12:15
In the scenario

I asked auto  --> configured in aquatemp as cool (but shown in HA as Auto)
I asked Cool  --> configured in aquatemp as Heat (but shown in HA as Cool)
I asked Heat -->  configured in aquatemp as Auto (but shown in HA as Cool)
I asked Off --> Went Off


[home-assistant_aqua_temp_2023-05-30T12-09-46.520Z.log](https://github.com/radical-squared/aquatemp/files/11599808/home-assistant_aqua_temp_2023-05-30T12-09-46.520Z.log)

**Comment by elad-bar** [comment] 2023-05-30 22:37
According to the original code, when extracting the temperature and mode, the code is the same:
```python
        if self._hvac_mode == HVAC_MODE_COOL:
            mode = 'R01'
        elif self._hvac_mode == HVAC_MODE_AUTO:
            mode = 'R03'
        else:
            mode = 'R02'
```

current:
```python
MODE_TEMPERATURE_OFF = "0"
MODE_TEMPERATURE_COOL = "1"
MODE_TEMPERATURE_HEAT = "2"
MODE_TEMPERATURE_AUTO = "3"

HVAC_MODE_MAPPING = {
    HVACMode.OFF: MODE_TEMPERATURE_OFF,
    HVACMode.COOL: MODE_TEMPERATURE_COOL,
    HVACMode.HEAT: MODE_TEMPERATURE_HEAT,
    HVACMode.AUTO: MODE_TEMPERATURE_AUTO,
}
```

problem was with mapping of performing actions (change HVAC mode):
```python
if hvac_mode == HVAC_MODE_COOL:
            value = "0"
            hm = HVAC_MODE_COOL
        elif hvac_mode == HVAC_MODE_HEAT:
            value = "1"
            hm = HVAC_MODE_HEAT
        elif hvac_mode == HVAC_MODE_AUTO:
            value = "2"
            hm = HVAC_MODE_AUTO
        elif hvac_mode == HVAC_MODE_OFF:
            code = "power"
            value = "0"
            hm = HVAC_MODE_OFF 
```

changed the mapping for action to be exactly as in the original code:
```python
HVAC_MODE_ACTION = {
    HVACMode.COOL: "0",
    HVACMode.HEAT: "1",
    HVACMode.AUTO: "2",
}
```

fix of actions will be part of v3.0.2

**Comment by migueldc73** [comment] 2023-05-31 06:41
I just upgrade to v3.0.2 and the mismatched mapping behaviour is still the same as in v3.0.1
Also, when HA reboots and Aqua_Temp restarts, it turns the HVAC off, so I have to manually restart.

**Comment by elad-bar** [comment] 2023-05-31 08:22
is it the turn off on restart issue introduced in this version?
about the mismatch - just to make sure we are aligned on the issue:
*Setting modes in HA is not aligned with Aqua Temp*
- Auto (in HA) -> Cool (in aquatemp)
- Cool (in HA) -> Heat (in aquatemp
- Heat (in HA) -> Auto (in Aquatemp)

What about presenting it? is it according to the  app?

thanks

**Comment by migueldc73** [comment] 2023-05-31 08:38
I performed some extra tests and can now confirm that the turning off on restart is just brief. The pump turns off and then back on, but only in HA, so it's probably just refreshing the UI.
But then again, the HP sometimes appears briefly as "OFF" and then back "ON" in HA when I change mode in the aquatemp app.
What has actually improved over v3.0.1 is that v3.0.2 now reads the status of the HP correctly as being ON when HA reboots.

The mapping is indeed like you mentioned and it works in both directions. So if I would select "HEAT" in the aquatemp app, it would still appear as Cool in HA. Or selecting Heat in HA would result aquatemp going into Auto

    Auto (in HA) -> Cool (in aquatemp)
    Cool (in HA) -> Heat (in aquatemp
    Heat (in HA) -> Auto (in Aquatemp)

**Comment by elad-bar** [comment] 2023-05-31 08:42
ok, will try to check it later today changing in the app, see how it reflects in HA vice versa,
target temperatures are ok between the modes for you?

I noticed that it takes time for the cloud to get updated, so it might be the delay you are experiencing,
anyway, will check it.

**Comment by migueldc73** [comment] 2023-05-31 09:02
The target temperatures are changed properly, but in the wrong modes.
I'll explain for v3.0.2:
- HA is in mode Heat -> Aquatemp is in mode Auto
- I change the temperature in HA from 28 to 30 deg while being in mode Heat (in HA)
- the temperature of mode Auto in Aquatemp changes also from 28 to 30

That behaviour was different in v3.0.1. There the temperature changed in the mismatched modes 
- HA is in mode Heat -> Aquatemp is in mode Auto
- I change the temperature in HA from 28 to 30 deg while being in mode Heat (in HA)
- the temperature of mode Auto in Aquatemp stays 
- but... if I then select Heat in Aquatemp, then I see the temp change from  28 to 30 in the Aquatemp Heat mode

Maybe when you did the remapping yesterday, it only affected the temperature and not the status.

Another I mentioned is that when I change the fan speed to Low in Aquatemp, the HP appears as OFF in HA.

**Comment by legantois** [comment] 2023-05-31 18:14
i confirm v3.0.2 is not imporving the situation

still
Auto (in HA) -> Cool (in aquatemp)
Cool (in HA) -> Heat (in aquatemp
Heat (in HA) -> Auto (in Aquatemp)

regarding temperature HA climate is consistent with himself and is showing what should be the temperature associated with the mode it believes it is in, but the temperature in aquatemp is not modified

**Comment by elad-bar** [comment] 2023-06-01 00:05
seems that I found the mapping issue and also found that set temp / mode was running bit differently than the app and aligned it, v3.0.3 will be tested during the weekend.

thanks

**Comment by migueldc73** [comment] 2023-06-04 15:45
I just installed v3.0.3 and it all seems to run fine now, except for a new issue, which occurred before intermittently but now consistently : when restarting HA, the Aquatemp heatpump is turned off. Both in HA as in the Aquatemp app.
But the mapping of the modes and temperature is fine.

**Comment by elad-bar** [comment] 2023-06-04 16:42
please upgrade to v3.0.4, if still happens, please set debug log level for component and send logs after HA is restarting,
I need to see what triggers that action as i can't reproduce that issue

thanks

**Comment by migueldc73** [comment] 2023-06-04 16:55
ignore my comments, the shutting off is caused by one of my automations which kicks in when I restart

My apologies

**Comment by elad-bar** [comment] 2023-06-04 18:02
that's ok :)

**Comment by elad-bar** [comment] 2023-06-05 08:39
can you pls close the issue?

thanks

**Closed as completed** 2023-06-09 07:15 UTC
